
CREATE TABLE cities
(
    id_city INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id_city)
);

CREATE TABLE document_types
(
    id_document_type INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_document_types PRIMARY KEY (id_document_type)
);

CREATE TABLE months
(
    id_month INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_months PRIMARY KEY (id_month)
);

CREATE TABLE roles
(
    id_role INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id_role)
);

DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    document_number        BIGINT       NOT NULL,
    document_type_id       INTEGER,
    id_city                INTEGER,
    id_role                INTEGER,
    full_name              VARCHAR(255) NOT NULL,
    phone_number           VARCHAR(255) NOT NULL,
    email                  VARCHAR(255) NOT NULL,
    address                VARCHAR(255),
    password               VARCHAR(255) NOT NULL,
    profile_image_link     VARCHAR(255),
    is_enabled             BOOLEAN,
    account_no_expired     BOOLEAN,
    account_no_locked      BOOLEAN,
    credentials_no_expired BOOLEAN,
    CONSTRAINT pk_users PRIMARY KEY (document_number)
);

-- E-learning: base tables

CREATE TABLE courses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                           NOT NULL,
    description VARCHAR(2000),
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE course_modules
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id   BIGINT                                   NOT NULL,
    title       VARCHAR(255)                             NOT NULL,
    content     TEXT,
    order_index INTEGER,
    CONSTRAINT pk_course_modules PRIMARY KEY (id)
);

CREATE TABLE user_courses
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_document_number BIGINT                                   NOT NULL,
    course_id            BIGINT                                   NOT NULL,
    progress_percentage  DOUBLE PRECISION                         NOT NULL DEFAULT 0,
    enrolled_at          TIMESTAMP                                NOT NULL,
    CONSTRAINT pk_user_courses PRIMARY KEY (id)
);

CREATE TABLE module_completions
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_document_number BIGINT                                   NOT NULL,
    module_id            BIGINT                                   NOT NULL,
    completed_at         TIMESTAMP                                NOT NULL,
    CONSTRAINT pk_module_completions PRIMARY KEY (id)
);
