-- Create categories table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

-- Unique constraint on name
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_name = 'uc_categories_name'
          AND table_name = 'categories'
    ) THEN
        ALTER TABLE categories ADD CONSTRAINT uc_categories_name UNIQUE (name);
    END IF;
END $$;

-- Seed categories
INSERT INTO categories (name) VALUES ('Backend') ON CONFLICT DO NOTHING;
INSERT INTO categories (name) VALUES ('Frontend') ON CONFLICT DO NOTHING;
INSERT INTO categories (name) VALUES ('Testing') ON CONFLICT DO NOTHING;
INSERT INTO categories (name) VALUES ('Data Science') ON CONFLICT DO NOTHING;

-- Add category_id column to courses if missing
ALTER TABLE courses ADD COLUMN IF NOT EXISTS category_id BIGINT;

-- Add FK constraint
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_courses_on_category'
          AND table_name = 'courses'
    ) THEN
        ALTER TABLE courses ADD CONSTRAINT fk_courses_on_category FOREIGN KEY (category_id) REFERENCES categories (id);
    END IF;
END $$;